#!/bin/sh

export PATH=/sbin:/bin

/bin/mount -n -t proc  /proc  /proc 
/bin/mount -n -t sysfs none /sys

/sbin/ifconfig lo 127.0.0.1 up
/sbin/route add 127.0.0.1 lo &

/sbin/ifconfig eth0 10.0.2.3 netmask 255.255.255.0 up
/sbin/ip route add default via 10.0.2.2

/bin/mount -n -o  remount,rw  / 
/bin/mount -av


echo "Welcome to my tiny Linux ... "
